### PR TITLE
Stage back end

### PR DESCRIPTION
**Pull request by jason25840**
I am getting functionality. I am not sure my errors are implemented correctly, but I eagerly await your review.

### CODE REVIEW

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [ ] `package.json` contains the `devDependencies` needed for the linter to work correctly
		 _Please install `eslint-config-airbnb-base`, `eslint-config-prettier`, and an `eslint` version lower than 9.0.0: https://prnt.sc/8FPYjhyTiBgK. Otherwise, the ESLint configuration file will not work, as the latest versions of ESLint require the new configuration file format. However, you can use the previous version._
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
   - _The lint script should be added to the package.json file: ` "lint": "npx eslint ."`_
   - _The linter errors need to be fixed: https://prnt.sc/n5SrMVs4UyIA_
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
     - _Please define the errors correctly, they should start with uppercase: https://prnt.sc/OFl-0bBDX53A_
     - _Braces should be deleted from the import: https://prnt.sc/PFDM0fwqkkcN_
     - _The error handler should check the `statusCode` property: https://prnt.sc/mbPT0jTOg4-N_
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
     _A middleware for handling an unknown route should be added after all other routes. It should return the error with the 404 status code_
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
     _When creating a user, the password hash should not be returned. The `select: false` argument, which is specified in the model, only works with `find` methods, such as `find` or `findOne`. You can return other fields except password_
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
    _The article's data is not validated by the celebrate_
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
   _The database address should have a default value so that the code can function without a `.env` file when running in dev mode._
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
   _Please add the production server domain to the README file_
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
     _The point can be given after the production server check_
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.
     _The secret key should have a default value so that when running in dev mode, the code can function without a `.env` file._

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
   _Please separate the error handler from the error logger, they should be two different entities_
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [x]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 46

## Additional comments:
- According to the task the path for the login controller should be `signin`
- Please consider using `express-winston` for logging requests and errors. Here is the [link to the lesson n the platform](https://tripleten.com/trainer/web/lesson/ac99f83d-4bea-408d-8713-7b96be277293/?from=program)

**Comment by jason25840** [comment]
Ok, I have the lint issues resolved. The backend is deployed, but I am not sure if nginx is picking up the api route. I am goin g to submit because I do not have access to a tutor for a while. Thanks for the input!

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
   - _The lint script should be added to the package.json file: ` "lint": "npx eslint ."`_
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
     _`users` should be removed from the path: https://prnt.sc/9TOhB4SApUzw. Otherwise, signup and signin routes will have the redundant '/users' segment in their path_
   - _Since the domain name has `api.` in it, the additional `/api` added to the routes should be removed: https://prnt.sc/hDEfurTs6sgz_
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
     - _The error handler should have the fourth parameter `next`: `(err, req, res, next) `. Without it, the errors will be returned incorrectly. To avoid the linter error you can add this rule to the settings: `"no-unused-vars": ["error", { "argsIgnorePattern": "next" }], `_
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
     - _The 'articleValidation' validation function should be connected to the route_
     - _The parameter `articleId` also should be validated by the 'celebrate'_
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
     _Please verify the presence of the `.env` file on the server and check the value of the secret key within it, as the same key appears to be used for both development and production modes._
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
   _ The middleware for handling an unknown route should also be moved to the index.js file_
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
   _ The middleware for handling an unknown route violates the principle of centralized error handling. Instead of returning the response directly, it should throw the corresponding exception._
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [x]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 48

## Additional comments:
- Please consider using `express-winston` for logging requests and errors. Here is the [link to the lesson n the platform](https://tripleten.com/trainer/web/lesson/ac99f83d-4bea-408d-8713-7b96be277293/?from=program)

**Comment by jason25840** [comment]
Back at ya Aisalkyn. Thank You again!

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [ ] `POST /articles` creates an article with the data passed inside the request body.
     - _The validation function doesn’t allow the `link` field and instead requires the `url` field. However, the field is received as `link` in `req.body` but saved in the database as `url`: https://prnt.sc/hOo0BHepGB9X. The same issue applies to the `image` field. The field names depend on how they are provided by the third-party News API in `req.body` and should match in both the Mongoose schema and the validation schema. Please make the necessary changes_
     - _The app is currently crashing due to the request logger: https://prnt.sc/cfLzWwuBkFtO. You can use the `express-winston` module to add loggers to the Express app. Here’s how the educational program suggested creating the loggers: https://prnt.sc/KcMAkey8eI2B._
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [x]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 78

## Additional comments:

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
   _There is one ESlint error: https://prnt.sc/IkCS0Fc6zzlh_
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET /articles` returns all articles saved by the user.
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [x]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 96

## Additional comments:
- Since the domain name has `api` in it, the additional `/api` added to the routes should be removed: https://prnt.sc/XZSwhtr9xkrf. 
- The errorLogger should be connected before the error handlers: https://prnt.sc/7xY3egR71mUe

**Pull request merged**
